name: Lint

on: [push, pull_request]

jobs:
  inspect-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare to install
      run: sudo apt-get update
    - name: python for cpplint
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: git submodule update
      run: |
        git submodule update --init --recursive
    - name: install tools
      run: |
        pip install cpplint
        sudo apt-get install -y clang-tidy
        sudo apt-get install -y cppcheck
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
    - name: cpplint
      run: |
        find monitor/ -type f \( -name "*.cpp" -o -name "*.h" \) ! -path "monitor/test/*" | xargs cpplint --filter=-legal --linelength=100

    - name: cppcheck
      run: |
        cppcheck  monitor/ --exclude=monitor/test --enable=all --error-exitcode=1 --suppress=missingIncludeSystem --std=c++20

    - name: clang-format
      run: |
        find monitor/ -type f \( -name "*.cpp" -o -name "*.h" \) ! -path "monitor/test/*" | xargs clang-tidy -p=.
